In [ ]:
#
# hw4pr1births_modeler:  birth classification by month + day    (above/below median: 190942)
#

In [ ]:
#
# SUGGESTION:  
# 
#       +++ copy-paste-and-alter from the iris-modeling notebook to here +++
#
# This approach has the advantage of more deeply "digesting" the iris workflow...
#      ...altering the parts that don't transfer, and taking the parts that do
#

In [1]:
# libraries!
import numpy as np      # numpy is Python's "array" library
import pandas as pd  

In [2]:
cleaned_filename = "births_cleaned.csv"
df_tidy = pd.read_csv(cleaned_filename)   # encoding="utf-8" et al.
print(f"{cleaned_filename} : file read into a pandas dataframe.")
df_tidy

births_cleaned.csv : file read into a pandas dataframe.


month  day  births  above/below median
0        1    1  160369                   0
1        1    2  169896                   0
2        1    3  180036                   0
3        1    4  182854                   0
4        1    5  184145                   0
..     ...  ...     ...                 ...
367     12   27  194006                   1
368     12   28  201768                   1
369     12   29  204806                   1
370     12   30  206894                   1
371     12   31  194368                   1

[366 rows x 4 columns]

In [3]:
# drop births 
ROW = 0
COLUMN = 1
df_model1 = df_tidy.drop( 'births', axis=COLUMN )
df_model1

month  day  above/below median
0        1    1                   0
1        1    2                   0
2        1    3                   0
3        1    4                   0
4        1    5                   0
..     ...  ...                 ...
367     12   27                   1
368     12   28                   1
369     12   29                   1
370     12   30                   1
371     12   31                   1

[366 rows x 3 columns]

In [19]:
# creating index of names w/o births
COLUMNS = df_model1.columns            # "list" of columns
print(f"COLUMNS is {COLUMNS}\n")  
  # It's a "pandas" list, called an Index
  # use it just as a Python list of strings:
print(f"COLUMNS[0] is {COLUMNS[0]}\n")

# let's create a dictionary to look up any column index by name
COL_INDEX = {}
for i, name in enumerate(COLUMNS):
    COL_INDEX[name] = i  # using the name (as key), look up the value (i)
print(f"COL_INDEX is {COL_INDEX}\n\n")

BIRTH_TREND = ['below', 'above']
OUTCOME_INDEX = {'below':0, 'above':1}


def birth_trends(median):
    """ return the species index (a unique integer/category) """
    #print(f"converting {speciesname}...")
    return OUTCOME_INDEX[median]

# Let's try it out...
for median in BIRTH_TREND:
    print(f"{median} maps to {OUTCOME_INDEX[median]}")


COLUMNS is Index(['month', 'day', 'above/below median'], dtype='object')

COLUMNS[0] is month

COL_INDEX is {'month': 0, 'day': 1, 'above/below median': 2}


below maps to 0
above maps to 1


In [12]:
A = df_model1.to_numpy()    # .values gets the numpy array

A = A.astype('float64')  # so many types:  www.tutorialspoint.com/numpy/numpy_data_types.htm
print(A)

[[ 1.  1.  0.]
 [ 1.  2.  0.]
 [ 1.  3.  0.]
 ...
 [12. 29.  1.]
 [12. 30.  1.]
 [12. 31.  1.]]


In [22]:
NUM_ROWS, NUM_COLS = A.shape
print(f"\nThe dataset has {NUM_ROWS} rows and {NUM_COLS} cols")


The dataset has 366 rows and 3 cols


In [21]:
# let's use all of our variables, to reinforce that we have
# (1) names...
# (2) access and control...

# choose a row index, n:
n = 42
print(f"day #{n} is {A[n]}")

for i in range(len(COLUMNS)):
    colname = COLUMNS[i]
    value = A[n][i]
    print(f"  Its {colname} is {value}")

median_index = COL_INDEX['above/below median']
median = int(round(A[n][median_index]))
median_outcome = BIRTH_TREND[median]
print(f"  Its median is {median_outcome} (i.e., {median})")

day #42 is [ 2. 12.  1.]
  Its month is 2.0
  Its day is 12.0
  Its above/below median is 1.0
  Its median is above (i.e., 1)


In [23]:
print("+++ Start of data definitions +++\n")
X_all = A[:,0:2]  # X (features) ... is all rows, columns 0, 1
y_all = A[:,2]    # y (labels) ... is all rows, column 2 only

print(f"y_all (just the labels/species)   are \n {y_all}")
print(f"X_all (just the features) are \n {X_all}")

+++ Start of data definitions +++

y_all (just the labels/species)   are 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0. 1.
 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 1.
 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 

In [24]:
# we scramble the labeled medians 
# remove (potential) dependence on its ordering: 
indices = np.random.permutation(len(y_all))  # indices is a permutation-list

# we scramble both X and y, necessarily with the same permutation
X_labeled = X_all[indices]              # we apply the _same_ permutation to each!
y_labeled = y_all[indices]              # again...
print(f"The scrambled labels/species are \n {y_labeled}")
print(f"The corresponding data rows are \n {X_labeled}")

The scrambled labels/species are 
 [0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 0.
 1. 1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0.
 0. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0.
 0. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0. 1.
 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1.
 1. 0. 0. 1. 0. 0. 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0.
 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 0. 0.
 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 1. 0. 0. 1.
 1. 1. 1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 0. 1. 1.
 0. 0. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0.
 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0.
 1. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0. 1. 0. 1.
 1. 1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 1. 0. 1. 1. 0. 0. 1. 0.
 1. 0. 1. 1. 0. 

In [25]:
#
# We next separate into test data and training data ... 
#    + We will train on the training data...
#    + We will _not_ look at the testing data to build the model
#
# Then, afterward, we will test on the testing data -- and see how well we do!
#

#
# a common convention:  train on 80%, test on 20%    Let's define the TEST_PERCENT
#

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.2, random_state=42)

print(f"training with {len(y_train)} rows;  testing with {len(y_test)} rows\n" )

print(f"Held-out data... (testing data: {len(y_test)})")
print(f"y_test: {y_test}")
print(f"X_test (a few rows): {X_test[0:5,:]}")  # 5 rows
print()
print(f"Data used for modeling... (training data: {len(y_train)})")
print(f"y_train: {y_train}")
print(f"X_train (a few rows): {X_train[0:5,:]}")  # 5 rows

training with 292 rows;  testing with 74 rows

Held-out data... (testing data: 74)
y_test: [1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1.
 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1.
 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1. 0. 0. 1.
 1. 1.]
X_test (a few rows): [[ 7. 12.]
 [ 2.  3.]
 [ 1. 16.]
 [11.  6.]
 [ 2. 27.]]

Data used for modeling... (training data: 292)
y_train: [0. 1. 0. 1. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0.
 0. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0.
 0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1.
 1. 1. 0. 1. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 0.
 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0.
 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0.
 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 

In [30]:
# to do this, we use "cross validation"
#
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

#
# cross-validation splits the training set into two pieces:
#   + model-building and model-validation. We'll use "build" and "validate"
#
best_k = 84 # Not correct!
best_accuracy = 0.0  # also not correct...

# Note that we are cross-validating using only our TEST data!
for k in range(1,85):
    knn_cv_model = KNeighborsClassifier(n_neighbors=k)   # build knn_model for every k!
    cv_scores = cross_val_score( knn_cv_model, X_train, y_train, cv=5 )  # cv=5 means 80/20
    # print(cv_scores)  # just to see the five scores... 
    average_cv_accuracy = cv_scores.mean()  # mean() is numpy's built-in average function 
    print(f"k: {k:2d}  cv accuracy: {average_cv_accuracy:7.4f}")

    
# assign best value of k to best_k
    if average_cv_accuracy > best_accuracy:
        best_k = k    # at the moment this is incorrect   TO DO for hw4pr1: fix this...
        best_accuracy = average_cv_accuracy
# you'll need to use the loop above to find and remember the real best_k

print(f"best_k = {best_k}  yields the highest average cv accuracy.")  # print the best one



k:  1  cv accuracy:  0.8084
k:  2  cv accuracy:  0.7842
k:  3  cv accuracy:  0.8183
k:  4  cv accuracy:  0.7976
k:  5  cv accuracy:  0.8287
k:  6  cv accuracy:  0.8115
k:  7  cv accuracy:  0.8286
k:  8  cv accuracy:  0.8185
k:  9  cv accuracy:  0.8354
k: 10  cv accuracy:  0.8321
k: 11  cv accuracy:  0.8319
k: 12  cv accuracy:  0.8149
k: 13  cv accuracy:  0.8456
k: 14  cv accuracy:  0.8218
k: 15  cv accuracy:  0.8285
k: 16  cv accuracy:  0.8184
k: 17  cv accuracy:  0.8251
k: 18  cv accuracy:  0.8285
k: 19  cv accuracy:  0.8148
k: 20  cv accuracy:  0.8148
k: 21  cv accuracy:  0.8080
k: 22  cv accuracy:  0.8149
k: 23  cv accuracy:  0.8286
k: 24  cv accuracy:  0.8148
k: 25  cv accuracy:  0.8149
k: 26  cv accuracy:  0.8251
k: 27  cv accuracy:  0.8149
k: 28  cv accuracy:  0.8217
k: 29  cv accuracy:  0.8252
k: 30  cv accuracy:  0.8252
k: 31  cv accuracy:  0.8286
k: 32  cv accuracy:  0.8354
k: 33  cv accuracy:  0.8184
k: 34  cv accuracy:  0.8149
k: 35  cv accuracy:  0.8150
k: 36  cv accuracy: 

In [31]:
knn_model_tuned = KNeighborsClassifier(n_neighbors=best_k)   # here, we use the best_k!

# we train the model (one line!)
knn_model_tuned.fit(X_train, y_train)                              # yay!  trained!
print(f"Created + trained a knn classifier, now tuned with a (best) k of {best_k}")  

# How does it do?!  The next cell will show...

Created + trained a knn classifier, now tuned with a (best) k of 13


In [32]:
def compare_labels(predicted_labels, actual_labels):
    """ a more neatly formatted comparison """
    NUM_LABELS = len(predicted_labels)
    num_correct = 0
    
    for i in range(NUM_LABELS):
        p = int(round(predicted_labels[i]))         # round protects from fp error 
        a = int(round(actual_labels[i]))
        result = "incorrect"
        if p == a:  # if they match,
            result = ""       # no longer incorrect
            num_correct += 1  # and we count a match!

        print(f"row {i:>3d} : {BIRTH_TREND[p]:>12s} {BIRTH_TREND[a]:<12s}   {result}")   

    print()
    print("Correct:", num_correct, "out of", NUM_LABELS)
    return num_correct

In [33]:
# Re-create and re-run the  "Model-testing Cell"     How does it do with best_k?!
#
predicted_labels = knn_model_tuned.predict(X_test)
actual_labels = y_test

# Let's print them so we can compare...
print("Predicted labels:", predicted_labels)
print("Actual labels:", actual_labels)

# And, the overall results
num_correct = sum(predicted_labels == actual_labels)
total = len(actual_labels)
print(f"\nResults on test set:  {num_correct} correct out of {total} total.\n\n")

# Plus, we'll print our nicer table...
compare_labels(predicted_labels,actual_labels)

Predicted labels: [1. 0. 0. 1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1.
 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 1. 0. 1. 0. 0.
 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1. 0. 0. 1.
 1. 1.]
Actual labels: [1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1.
 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1.
 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1. 0. 0. 1.
 1. 1.]

Results on test set:  61 correct out of 74 total.


row   0 :        above above          
row   1 :        below below          
row   2 :        below below          
row   3 :        above below          incorrect
row   4 :        below below          
row   5 :        above above          
row   6 :        below above          incorrect
row   7 :        below below          
row   8 :        above below          incorrect
row   9 :        below below          
row  10 :        above below          incor

61

<br>

#### Final, big-picture question:  
+ Which phenomenon, iris-species or birthday-popularity, is more "modelable"?
+ ... at least, as these two datasets are concerned?!

Your thoughts... / why...
Iris species involves taking continuous data such as petal length and width and using these characteristics to sort the irises into catagories. I think there's a stronger relationship between iris characteristcs v iris species than a particular day warrenting more births. Birthday-popularity is also continous data being sorted into two catagories: above v below median births. It is difficult to use just the days and months to predict whether a day has higher births since there seems to be a less strong relationship between a particular day v. birthday-popularity. 

In [ ]:
#
# That's it!  Welcome to the world of model-building workflows!!    
#
#             Our prediction?  We'll be back for more ML! 
#

#
# In fact, the rest of the hw is to run more ML workflows:   (2)Digits, (3)Titanic, (ec)Housing, ...
#

In [ ]:
#
#  Regression! For birthdays... kNN Regressor?
#